# Generated by Django 3.0.7 on 2020-07-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='avatar',
            field=models.ImageField(default='profile_avatar/No_image_available.svg.png', max_length=255, upload_to='product_photos/'),
        ),
    ]
